name: Deploy Site to GitHub Pages

on:
  - push
  - workflow_dispatch

jobs:
  call-deploy:
    uses: comtextspace/comtext-builder-workflow/.github/workflows/deploy.yml@main
    with:
      url: null 

# Для добавления своего домена замените null на свой домен
#
# Например
# url: mysite.net

